name: Print Hello on Push

on:
  push:
    branches:
      - main
      - ci/github-actions

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v3
      
      - name: Dizer oi
        run: echo "Olá! Um push foi feito para a branch!"
