name: Teste de Calculadora

on:
  push:
    branches:
      - as2 # Agora, a ação vai rodar na branch 'as2' quando houver push
  pull_request:
    branches:
      - as2 # Quando houver PR na branch 'as2'

jobs:
  test:
    runs-on: ubuntu-latest # Define a máquina virtual onde o job será executado

    steps:
      # Passo 1: Checar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # A versão do Python que você quer usar

      # Passo 3: Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Se tiver um arquivo requirements.txt

      # Passo 4: Rodar os testes
      - name: Rodar os testes unitários
        run: |
          python -m unittest test_calculadora.py  # Roda os testes do arquivo de calculadora
